// Deterministic geometry for the isolated Pelagos Chartwright content seam.

import { ACT2_TIDE_ORDER, act2Authoring } from './act2Content.js'
import { ACT2_CHARTWRIGHT_POCKETS, ACT2_CHARTWRIGHT_CONNECTIONS } from './act2ChartwrightContent.js'
import { WAYFINDING_SURVEY_CONTRACTS } from './wayfinding.js'

function deepFreeze(value) { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); for (const nested of Object.values(value)) deepFreeze(nested) } return value }
const point = (x, y) => ({ x, y })
const spawn = (id, x, y, facing) => ({ id, x, y, facing })
const solid = (id, x, y, w, h) => ({ id, kind: 'solid', x, y, w, h })
const lane = (id, width, stateIds, points) => ({ id, width, stateIds, points })
const meta = (category, question, systemsUsed, reward, consequence, recovery, expectedMinutes, levelMin = 1, levelMax = 70) => act2Authoring({ category, dramaticQuestion: question, systemsUsed, durableReward: reward, downstreamConsequence: consequence, recoveryBehavior: recovery, expectedMinutes, originalityNotes: 'Uses public-domain Mediterranean sounding, beacon, harbor, and skiff practices; this Chartwright layout and civic navigation expression are original.', levelMin, levelMax })
const survey = (contract, x, y) => ({ id: `survey-${contract.id}`, kind: 'survey-marker', surveyContractId: contract.id, x, y, name: contract.bandId.replaceAll('-', ' '), label: `Survey ${contract.bandId.replaceAll('-', ' ')} bearing`, authoring: meta('world-entity', 'Can this bearing be checked by a traveler who carries the required chart?', ['wayfinding', 'exploration'], 'A valid survey grants its exact-once chart discovery and shortcut descriptor.', 'Its permanent shortcut is an optional future travel seam.', 'Cooldown practice and duplicate discovery are handled by the pure Wayfinding domain.', 2, contract.requiredLevel, contract.requiredLevel) })

const palette = deepFreeze({ name: 'pelagos-chartwright', sky: '#476d7c', skyLow: '#a9c4be', sea: '#17596b', sun: '#f3d99c', marble: '#c5c2a3', marbleMid: '#899f92', marbleShadow: '#526b68', stone: '#526a69', stoneDark: '#293e44', gold: '#d3ad59', glow: '#87ead5', ink: '#10242c', outline: '#091820', danger: '#ad5051', void: '#06151c', path: '#a4b7a4' })

export const ACT2_CHARTWRIGHT_RUNTIME_MAPS = deepFreeze({
  'chartwright-hall': {
    ...ACT2_CHARTWRIGHT_POCKETS['chartwright-hall'], bounds: { w: 960, h: 540 }, palette, themeId: 'pelagos-open-chart-hall', decorSetId: 'brass-sounding-tables',
    spawns: { 'from-pelagos': spawn('from-pelagos', 72, 286, 0), 'from-shoal': spawn('from-shoal', 888, 286, Math.PI), 'published-route': spawn('published-route', 480, 384, -Math.PI / 2) },
    entities: [
      { id: 'ianthe-chartwright', kind: 'npc', x: 290, y: 286, name: 'Ianthe', label: 'Ask Ianthe about the open chart', conversationId: 'act2-ianthe-chartwright-briefing', questAcceptance: { questId: 'cq-act2-ianthe-open-chart', trigger: 'talk' }, authoring: meta('world-entity', 'Will Ianthe publish a chart that can be corrected in public?', ['dialogue', 'wayfinding'], 'Ianthe begins the character route contract.', 'Her publication choice creates a future cross-act consequence seam.', 'Conversation remains restartable until its exact objective settles.', 2) },
      { id: 'naukleros-signal-keeper', kind: 'npc', x: 480, y: 286, name: 'Naukleros', label: 'Hear the signal keeper', conversationId: 'act2-naukleros-signal-shoal', questAcceptance: { questId: 'sq-act2-submerged-signal', trigger: 'talk' }, authoring: meta('world-entity', 'Can a signal keeper describe risk without selling the danger as spectacle?', ['dialogue', 'wayfinding'], 'Naukleros offers the optional signal route.', 'His warning directs the player to the shoal elite.', 'The dialogue reference is explicit and can be integrated without display-text inference.', 2) },
      { id: 'dorieus-route-clerk', kind: 'npc', x: 640, y: 286, name: 'Dorieus', label: 'Consult the route clerk', conversationId: 'act2-dorieus-published-route', authoring: meta('world-entity', 'Who records a shortcut once a public chart changes?', ['dialogue', 'choice'], 'Dorieus exposes the publication consequence seam.', 'His record can reflect the Ianthe choice later.', 'No dialogue effect is assumed until registry integration.', 2) },
      { id: 'chart-table', kind: 'station', stationId: 'chartwright-open-table', x: 400, y: 370, name: 'Open Chart Table', label: 'Work at the public chart table', questAcceptance: { questId: 'mqy-wayfinding-covenant-routes', trigger: 'station' }, authoring: meta('world-entity', 'Can a physical table make navigation work visible rather than remote?', ['wayfinding', 'crafting'], 'The table is the physical, collision-checked chart-crafting station.', 'It anchors material work to a visible civic place instead of a remote menu.', 'Station access is repeatable while crafting validation remains atomic.', 1) },
      survey(WAYFINDING_SURVEY_CONTRACTS[0], 250, 390), survey(WAYFINDING_SURVEY_CONTRACTS[1], 570, 390),
      { id: 'chartwright-reed-bed', kind: 'resource', x: 180, y: 330, name: 'Chartwright Reed Bed', label: 'Gather waterproof reeds', skillId: 'foraging', itemId: 'waterproof-reed', level: 1, xp: 14, authoring: meta('gathering-resource', 'Can common reeds become durable navigation material?', ['foraging', 'inventory'], 'The reed node supplies a chart component.', 'It supports physical chart-tool recipes.', 'Respawn and capacity checks remain future shared-resource integration seams.', 2) },
      { id: 'brass-pin-cache', kind: 'resource', x: 760, y: 360, name: 'Brass Pin Cache', label: 'Salvage brass chart pins', skillId: 'quarrying', itemId: 'brass-chart-pin', level: 10, xp: 20, authoring: meta('gathering-resource', 'Can a harbor salvage cache reward careful chart repair?', ['quarrying', 'inventory'], 'The pins supply a mid-band chart component.', 'They make future tools visibly sourced in Pelagos.', 'Level and capacity failure remain atomic at reducer integration.', 2, 10, 15) },
      { id: 'hall-ink-vats', kind: 'resource', x: 820, y: 250, name: 'Blue Ink Vats', label: 'Draw tidal ink', skillId: 'foraging', itemId: 'tidal-ink', level: 15, xp: 24, authoring: meta('gathering-resource', 'Can a shared ink vat make an official chart editable?', ['foraging', 'inventory'], 'Tidal ink supplies advanced chart publication.', 'It feeds the open-chart crafting loop.', 'Its resource state is deterministic and reload-safe once integrated.', 2, 15, 20) },
    ],
    exits: [
      { id: 'chartwright-hall-to-pelagos-harbor', x: 38, y: 286, toMapId: 'pelagos-harbor', spawnId: 'from-chartwright', returnSpawnId: 'from-pelagos', kind: 'foot', gate: [] },
      { id: 'chartwright-hall-to-signal-shoal', x: 922, y: 286, toMapId: 'submerged-signal-shoal', spawnId: 'from-hall', returnSpawnId: 'from-shoal', kind: 'skiff', gate: [] },
    ], collisions: [solid('hall-north-shelves', 34, 42, 260, 80), solid('hall-north-archive', 650, 42, 270, 80), solid('hall-south-benches-left', 40, 454, 270, 46), solid('hall-south-benches-right', 650, 454, 270, 46)],
    traversalLanes: [lane('hall-main', 80, ACT2_TIDE_ORDER, [point(38, 286), point(290, 286), point(480, 286), point(640, 286), point(922, 286)]), lane('hall-survey-floor', 62, ACT2_TIDE_ORDER, [point(250, 390), point(400, 370), point(570, 390)]), lane('hall-material-aisle', 56, ACT2_TIDE_ORDER, [point(640, 286), point(760, 360), point(820, 250)]), lane('hall-chart-table-aisle', 74, ACT2_TIDE_ORDER, [point(290, 286), point(250, 390), point(400, 370), point(570, 390), point(640, 286)])],
    decor: [], tide: { initialStateId: 'ebb', laneIds: ['hall-main', 'hall-survey-floor', 'hall-material-aisle'], wellIds: [], skiffNodeIds: [], ropeLiftIds: [] },
  },
  'submerged-signal-shoal': {
    ...ACT2_CHARTWRIGHT_POCKETS['submerged-signal-shoal'], bounds: { w: 960, h: 540 }, palette: { ...palette, name: 'submerged-signal-shoal', sky: '#274f63', sea: '#0c4b60' }, themeId: 'pelagos-submerged-signal-shoal', decorSetId: 'drowned-buoy-reef',
    spawns: { 'from-hall': spawn('from-hall', 72, 286, 0), 'from-anchorage': spawn('from-anchorage', 888, 286, Math.PI), 'shoal-cleared': spawn('shoal-cleared', 480, 390, -Math.PI / 2) },
    entities: [
      { id: 'signal-buoy', kind: 'station', stationId: 'signal-buoy-workbench', x: 480, y: 390, name: 'Drowned Signal Buoy', label: 'Work at the drowned signal buoy', postEliteInteraction: { questId: 'sq-act2-submerged-signal', objectiveId: 'relight-public-buoy', requiresEncounterId: 'enc-act2-submerged-signal-reef' }, authoring: meta('world-entity', 'Can a repaired buoy make danger visible before it becomes a shortcut?', ['wayfinding', 'crafting'], 'The buoy is the physical, collision-checked late-band crafting station.', 'Its station state is a later travel-copy and signal-repair consequence seam.', 'The post-combat spawn keeps the station reachable after reload.', 2) },
      survey(WAYFINDING_SURVEY_CONTRACTS[2], 290, 370), survey(WAYFINDING_SURVEY_CONTRACTS[3], 610, 370), survey(WAYFINDING_SURVEY_CONTRACTS[4], 760, 250),
      { id: 'shoal-kelp-skein', kind: 'resource', x: 190, y: 350, name: 'Shoal Kelp Skein', label: 'Gather buoy kelp', skillId: 'foraging', itemId: 'buoy-kelp', level: 25, xp: 36, authoring: meta('gathering-resource', 'Can storm-resistant kelp become a public safety material?', ['foraging', 'inventory'], 'The kelp supplies signal repairs.', 'It adds a shoal-specific physical source for chart tools.', 'Gathering has deterministic capacity and respawn seams.', 2, 25, 30) },
      { id: 'reef-glass-vein', kind: 'resource', x: 690, y: 340, name: 'Reef Glass Vein', label: 'Mine reef glass', skillId: 'quarrying', itemId: 'reef-glass', level: 35, xp: 50, authoring: meta('gathering-resource', 'Can fractured reef glass become a precise survey lens?', ['quarrying', 'inventory'], 'Reef glass supplies advanced bearing tools.', 'It gives later charts a geographic source.', 'Level and capacity checks are atomic once the shared resource reducer owns it.', 2, 35, 40) },
      { id: 'storm-lantern-fish', kind: 'resource', x: 820, y: 220, name: 'Storm Lantern Fish', label: 'Fish for phosphor oil', skillId: 'fishing', itemId: 'phosphor-oil', level: 45, xp: 68, authoring: meta('gathering-resource', 'Can a risky fishery provide light without making the reef safe?', ['fishing', 'inventory'], 'Phosphor oil supplies mastery signal materials.', 'It rewards a return trip with a distinct fishing use.', 'Respawn is deterministic and capacity failure grants nothing.', 2, 45, 50) },
    ],
    exits: [
      { id: 'signal-shoal-to-chartwright-hall', x: 38, y: 286, toMapId: 'chartwright-hall', spawnId: 'from-shoal', returnSpawnId: 'from-hall', kind: 'skiff', gate: [] },
      { id: 'signal-shoal-to-storm-anchorage', x: 922, y: 286, toMapId: 'storm-anchorage', spawnId: 'from-signal-shoal', returnSpawnId: 'from-anchorage', kind: 'skiff', gate: [] },
      { id: 'combat-act2-submerged-signal-reef', x: 480, y: 286, kind: 'combat', encounterId: 'enc-act2-submerged-signal-reef', label: 'Challenge the bell-reef cartographer', gate: [] },
    ], collisions: [solid('shoal-north-reef-left', 40, 42, 260, 82), solid('shoal-north-reef-right', 650, 42, 270, 82), solid('shoal-south-reef-left', 40, 458, 260, 44), solid('shoal-south-reef-right', 650, 458, 270, 44), solid('shoal-central-ruin', 438, 180, 84, 70)],
    traversalLanes: [lane('shoal-main', 80, ACT2_TIDE_ORDER, [point(38, 286), point(290, 286), point(480, 286), point(690, 286), point(922, 286)]), lane('shoal-signal-loop', 62, ACT2_TIDE_ORDER, [point(290, 286), point(290, 370), point(480, 390), point(610, 370), point(690, 286)]), lane('shoal-mastery-rise', 58, ACT2_TIDE_ORDER, [point(610, 370), point(690, 320), point(760, 250), point(820, 220)])],
    decor: [], tide: { initialStateId: 'ebb', laneIds: ['shoal-main', 'shoal-signal-loop', 'shoal-mastery-rise'], wellIds: [], skiffNodeIds: [], ropeLiftIds: [] },
  },
})

export function act2ChartwrightRuntimeMapById(mapId) { return ACT2_CHARTWRIGHT_RUNTIME_MAPS[mapId] || null }
export function act2ChartwrightRuntimeEntityById(mapId, entityId) { const map = act2ChartwrightRuntimeMapById(mapId); return map?.entities.find((entity) => entity.id === entityId) || null }
export function act2ChartwrightRuntimeExitById(exitId) { return Object.values(ACT2_CHARTWRIGHT_RUNTIME_MAPS).flatMap((map) => map.exits).find((exit) => exit.id === exitId) || null }

export const ACT2_CHARTWRIGHT_CONNECTION_IDS = deepFreeze(ACT2_CHARTWRIGHT_CONNECTIONS.map((connection) => connection.id))
